api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: bombermanonline-infra_default
  file:
    directory: "/etc/traefik"
#    watch: true
  consulCatalog:
    endpoint:
      address: "consul:8500"
    exposedByDefault: true
    prefix: "traefik"
    refreshInterval: 15s
    requireConsistent: false
    stale: false


log:
  level: INFO


accessLog:
  filePath: "/var/log/traefik/access.log"

#experimental:
#  plugins:
#    extractCookie:
#      moduleName: "github.com/v-electrolux/extractcookie"
#      version: "v1.0.1"

experimental:
  localPlugins:
    extractCookie:
      moduleName: extractcookie